name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Caller's build
        run: echo caller
      - id: composite
        uses: outsideris/actions-test@main
        with:
          name: 'Outsider'
      - run: echo result = $RESULT
        env:
          RESULT: ${{ steps.composite.outputs.result }}
      
