name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Name'
        required: true
      tags:
        description: 'Debug Mode'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
