name: Release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  deploy-dev:
    needs: build
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: echo dev
  deploy-prod:
    needs: deploy-dev
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - run: echo prod
      
