name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          gh api /repos/outsideris/actions-test/dispatches \
          -f event_type='trigger'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
