name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo 'Ran build'
  call-lint:
    uses: outsideris/actions-test/.github/workflows/lint.yaml@main
    with:
      name: outsider
    secrets:
      API_KEY: ${{ secrets.API_KEY }}
