name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Caller's build
        run: echo caller
      - uses: outsideris/actions-test@main
        with:
          name: 'Outsider'
